[[streams]]
city   = "Sredot / Ashkelon"
label   = "Sredot / Ashkelon - Rawcasts"
link  = "https://www.youtube.com/watch?v=Drucm6lGLzQ&ab_channel=rawcasts"
kind  = "video"

[[streams]]
city   = "Sredot"
label   = "Sredot 1"
link  = "https://www.youtube.com/watch?v=3kAmf3_A0jc&ab_channel=Reuters"
kind  = "video"

[[streams]]
city   = "Sredot"
label   = "Sredot 2"
link  = "https://www.youtube.com/watch?v=k7yvgD9oiXs&ab_channel=MARCA"
kind  = "video"

[[streams]]
city   = "Hula Nature Reserve"
label   = "Hula Nature Reserve"
link  = "https://www.youtube.com/watch?v=05CF-R1-j9c"
kind  = "video"

[[streams]]
city   = "Safed"
label   = "Safed"
link  = "https://www.weather2day.co.il/zefat-webcam"
kind  = "video"

[[streams]]
city   = "Report"
label   = "Report - Al Jazeera"
link  = "https://www.youtube.com/watch?v=gCNeDWCI0vo"
kind  = "video"

[[streams]]
city   = "Report"
label  = "Report TRT World"
link   = "https://www.youtube.com/watch?v=5VF4aor94gw"
kind  = "video"

[[streams]]
city   = "Report"
label  = "Report - Sky News"
link   = "https://www.youtube.com/watch?v=9Auq9mYxFEE"
kind  = "video"

[[streams]]
city   = "Report"
label  = "Report - France 24"
link   = "https://www.youtube.com/watch?v=tkDUSYHoKxE"
kind  = "video"

[[streams]]
city   = "Report"
label  = "Report - NDTV"
link   = "https://www.youtube.com/watch?v=4ppJqfdt0SY"
kind  = "video"

[[streams]]
city   = "X"
label  = "X"
link   = ""
kind  = "video"